name: CaptainSayedApp
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.11.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  pigeon: ^0.2.4
  audioplayers: ^0.20.1
  provider: ^5.0.0
  animated_button: ^0.2.0
  google_fonts: ^2.3.2
  page_transition: ^2.0.5
  # youtube_player_flutter: ^7.0.0+7
  intl: ^0.17.0
  shared_preferences: ^2.0.13
  percent_indicator: ^4.2.1
  url_launcher: ^6.0.20
  rxdart: ^0.27.3
  firebase_core: ^1.15.0
  # cloud_firestore: ^0.14.0
  sizer: ^2.0.15
  firebase_auth: ^3.3.15
  path_provider: ^2.0.9
  image_picker: ^0.8.5
  path: ^1.8.0
  awesome_dialog: ^2.2.0
  # flutter_email_sender: ^3.0.1
  google_sign_in: ^5.3.0
  assets_audio_player: ^3.0.4+1
  http: ^0.13.4
#  flutter_facebook_login: ^3.0.0
#   loading_indicator: ^1.2.0
  dots_indicator: ^2.1.0
  json_annotation: ^4.4.0
  cached_network_image: ^3.2.0
  splashscreen: ^1.3.5
  dio: ^4.0.6
  flutter_facebook_auth: ^4.3.4
  font_awesome_flutter: ^10.1.0
  favorite_button: ^0.0.4

  # video_player: ^1.0.1
  # chewie: any
  meedu_player: ^0.5.0-nullsafety.1
  wakelock: ^0.6.1+2
  full_screen_image: any
  flutter_local_notifications: ^9.4.0
  flutter_svg: ^1.0.3
  numberpicker: ^2.1.1
  vertical_weight_slider: ^2.4.0
  rulers: ^1.0.7
  getwidget: ^2.0.5

  flutter_switch: ^0.3.2
  syncfusion_flutter_sliders: ^20.1.51
  # audioplayers: ^0.17.2
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.4
  animations: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.1.10
  json_serializable: ^6.1.6


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/images/getfit.png
    - assets/audio/tick.mp3
    - assets/audio/done.mp3


  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Medium.ttf
#        - asset: fonts/Raleway-Italic.ttf
    - family: Segoe UI
      fonts:
        - asset: assets/fonts/SEGOEUI.ttf
        - asset: assets/fonts/SEGOEUIB.ttf
          weight: 700
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo-Regular.ttf
        - asset: assets/fonts/Cairo-Bold.ttf
          weight: 700
    - family: AppIcon
      fonts:
        - asset: assets/icons/AppIcon.ttf